name: Linting

on:
  push:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install -U -r requirements.txt --no-cache-dir
      - run: pylint --rcfile=.pylintrc *.py
